[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project]
name = "jupyverse"
description = "A set of FPS plugins implementing a Jupyter server"
keywords = ["jupyter", "server", "fastapi", "plugins"]
dynamic = ["version"]
requires-python = ">=3.8"
dependencies = [
    "jupyverse-api",
    "fps-contents",
    "fps-kernels",
    "fps-terminals",
    "fps-nbconvert",
    "fps-yjs",
]

[[project.authors]]
name = "Jupyter Development Team"
email = "jupyter@googlegroups.com"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.license]
text = "BSD 3-Clause License"

[project.urls]
Homepage = "https://jupyter.org"

[project.optional-dependencies]
jupyterlab = [ "fps-jupyterlab",]
retrolab = [ "fps-retrolab",]
auth = [ "fps-auth",]
auth-fief = [ "fps-auth-fief",]
noauth = ["fps-noauth"]
test = [ "mypy", "types-setuptools", "pytest", "pytest-asyncio", "pytest-env", "requests", "websockets", "ipykernel",]
docs = [ "mkdocs", "mkdocs-material",]

[tool.hatch.envs.dev]
# TODO: if/when hatch gets support for  defining editable dependencies, the
# pre-install commands here and post-install commands in the matrix can be moved
# to the dependencies section
pre-install-commands = [
  "pip install -e ./jupyverse_api",
  "pip install -e ./plugins/contents",
  "pip install -e ./plugins/frontend",
  "pip install -e ./plugins/kernels",
  "pip install -e ./plugins/lab",
  "pip install -e ./plugins/nbconvert",
  "pip install -e ./plugins/terminals",
  "pip install -e ./plugins/yjs",
  "pip install -e ./plugins/resource_usage",
]
dependencies = ["fastapi>=0.87.0"]
features = ["test"]

[tool.hatch.envs.dev.overrides]
matrix.auth.post-install-commands = [
  { value = "pip install -e ./plugins/noauth", if = ["noauth"] },
  { value = "pip install -e ./plugins/auth", if = ["auth"] },
  { value = "pip install -e ./plugins/auth_fief", if = ["auth_fief"] },
]
matrix.frontend.post-install-commands = [
  { value = "pip install -e ./plugins/jupyterlab", if = ["jupyterlab"]},
  { value = "pip install -e ./plugins/retrolab", if = ["retrolab"]},
]

[[tool.hatch.envs.dev.matrix]]
frontend = ["jupyterlab", "retrolab"]
auth = ["noauth", "auth", "auth_fief"]

[tool.hatch.envs.dev.scripts]
test = "pytest ./tests -v"
lint = [
  "black --line-length 100 jupyverse ./plugins",
  "isort --profile=black jupyverse ./plugins",
]
typecheck = [
  "mypy jupyverse",
  "mypy jupyverse_api",
  "mypy plugins/frontend/fps_frontend",
  "mypy plugins/contents/fps_contents",
  "mypy plugins/kernels/fps_kernels",
  "mypy plugins/retrolab/fps_retrolab",
  "mypy plugins/jupyterlab/fps_jupyterlab",
  "mypy plugins/lab/fps_lab",
  "mypy plugins/auth/fps_auth",
  "mypy plugins/noauth/fps_noauth",
  "mypy plugins/auth_fief/fps_auth_fief",
  "mypy plugins/nbconvert/fps_nbconvert",
  "mypy plugins/yjs/fps_yjs",
  "mypy plugins/resource_usage/fps_resource_usage",
  "mypy plugins/terminals/fps_terminals",
  "mypy plugins/login/fps_login",
]

[tool.hatch.envs.docs]
features = ["docs"]

[tool.hatch.envs.docs.scripts]
build = "mkdocs build --clean --strict"
serve = "mkdocs serve --dev-addr localhost:8000"

[tool.check-manifest]
ignore = [ ".*",]

[tool.jupyter-releaser]
skip = [ "check-links", "check-manifest",]

[tool.flake8]
max-line-length = 100

[tool.jupyter-releaser.options]
python_packages = [
    "jupyverse_api:jupyverse-api",
    "plugins/noauth:fps-noauth",
    "plugins/auth:fps-auth",
    "plugins/auth_fief:fps-auth-fief",
    "plugins/contents:fps-contents",
    "plugins/frontend:fps-frontend",
    "plugins/jupyterlab:fps-jupyterlab",
    "plugins/kernels:fps-kernels",
    "plugins/lab:fps-lab",
    "plugins/nbconvert:fps-nbconvert",
    "plugins/retrolab:fps-retrolab",
    "plugins/terminals:fps-terminals",
    "plugins/yjs:fps-yjs",
    "plugins/resource_usage:fps-resource-usage",
    "plugins/login:fps-login",
    ".:jupyverse:jupyverse-api,fps-noauth,fps-auth,fps-auth-fief,fps-contents,fps-jupyterlab,fps-kernels,fps-lab,fps-frontend,fps-nbconvert,fps-retrolab,fps-terminals,fps-yjs,fps-resource-usage"
]

[tool.hatch.version]
path = "jupyverse/__init__.py"

[tool.pytest.ini_options]
asyncio_mode = "strict"
